wip

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -10,15 +10,13 @@ ENV_DIR=$3
 
 PROCFILE=$(cat "${ENV_DIR}/PROCFILE")
 
-if [[ -z "${PROCFILE}" ]]; then
+if [ -z "$PROCFILE" ]; then
     echo "PROCFILE was not set. Aborting" | indent
     exit 1
 fi
 
-cp "${BUILD_DIR}/${PROCFILE}" "${BUILD_DIR}/Procfile"
-
-if ! [ $? ]; then
-    echo "FAILED to copy a Procfile" | indent
+if ! cp "${BUILD_DIR}/${PROCFILE}" "${BUILD_DIR}/Procfile"; then
+    echo "FAILED to copy $PROCFILE" | indent
     exit 1
 fi
 
@@ -26,7 +24,11 @@ echo "Copied ${PROCFILE} as Procfile successfully" | indent
 
 APP_DIR=$(dirname "${BUILD_DIR}/${PROCFILE}")
 
-if [[ -f "${APP_DIR}/app.json" ]]; then
-    cp "${APP_DIR}/app.json" "${BUILD_DIR}/app.json"
+if [ -f "${APP_DIR}/app.json" ]; then
+    if ! cp "${APP_DIR}/app.json" "${BUILD_DIR}/app.json"; then
+	echo "FAILED to copy app.json" | indent
+	exit 1
+    fi
+
     echo "Copied ${APP_DIR}/app.json as app.json successfully" | indent
 fi
